<?php
class sfAssetsManagerConfigHandler extends sfYamlConfigHandler
{
public function execute($configFiles)
  {
    // Parse the yaml
    $config = $this->parseYamls($configFiles);
    $strConfig = var_export($config, true);
    $data = <<<EOF
<?php
// auto-generated by %s
// date: %s
return $strConfig;
EOF;
    $data = sprintf($data, __CLASS__, date('Y/m/d H:i:s'));
    
    return $data;
  }
}