all:
  sf_assets_manager_plugin:
    display_errors:       true      # Should it display errors and throw 500 ?
    autoload_helper:      true      # Automatically adds sfAssetsManager to default helpers
    enable_compressor:    false     # Enable merging and minifying files
    # Below options only take affect with compressor enbled
    filename_format:      %s.package # Format of the name where "%s" is the loaded package name
    encode_filename:      false     # Should the file generate be the given package name or encoded
    enable_supercache:    false     # Set to true to create file only once (prod purpose)
    js_dir:               %SF_ROOT_DIR%/data/assets/js  # Path for original javascript files
    css_dir:              %SF_ROOT_DIR%/data/assets/css # Path for original stylesheet files
    alter_response:       false    # When false, the regular helper can be used. When true, 
                                   # You should use the stylesheet_assets() and javascript_assets()
                                   # helper and the reponse will be modified after it is loaded
                                   # (useful for late rendering like loading from database)
    alter_response_tempcsstag: '<link rel="assetsmanager" />' # Temporary css tag to replaced 
                                                             # when response is altered
    alter_response_tempjstag: '<script type="assetsmanager"></script>' # Temporary js tag to replaced 
                                                             # when response is altered
